name: db_konversor
description: "Aplicativo para conversão entre unidades de potência e níveis logarítmicos."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icons/app_icon.png"

  adaptive_icon_background: "#050B18"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic